name: plan_b_fukuoka
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ▼ 최신 버전으로 업데이트 (호환성 해결)
  csv: ^6.0.0
  geolocator: ^13.0.0       # 위치 정보 최신 버전
  url_launcher: ^6.3.0      # 지도 열기 최신 버전
  file_picker: ^8.1.4       # [중요] 이 버전을 올려야 에러가 사라집니다!

  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/restaurants.csv

flutter_launcher_icons:
  android: "ic_launcher" # 안드로이드 아이콘 이름 설정
  ios: true              # iOS 아이콘 생성 활성화
  image_path: "assets/icon.png" # 준비한 이미지 경로
  min_sdk_android: 21 # 안드로이드 최소 SDK 버전 (선택사항)